#!/bin/bash
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VCS_REF=$(echo ${GIT_SHA1} | cut -b 1-7)

env

docker build \
       --build-arg micropiece_version=$SOURCE_BRANCH \
       --build-arg VCS_REF=${VCS_REF} \
       --build-arg BUILD_DATE=${BUILD_DATE} \
       -t $IMAGE_NAME .
