#!/bin/bash
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VCS_REF=$SOURCE_COMMIT
VCS_REF=$(echo ${VCS_REF} | cut -b 1-7)

env

docker build \
       --build-arg BRANCH=$SOURCE_BRANCH \
       --build-arg VCS_REF=${VCS_REF} \
       --build-arg BUILD_DATE=${BUILD_DATE} \
       -t $IMAGE_NAME .
